=== lyukasgumi/KLJDUJ_XMLgyak/XMLTaskKLJDUJ/XMLSchemaKLJDUJ.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!--XML felepitese -->

  <xs:element name="Covid19onkenteslogisztika">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Mentoallomasok">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Mentoallomas" type="Mentoallomas" minOccurs="0" maxOccurs="19"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="Jarmuvek">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Jarmu" type="Jarmu" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        
        <xs:element name="Hasznalat_Lista">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Hasznalja" type="Hasznalja" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        
        <xs:element name="Szemelyzetek">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Szemelyzet" type="Szemelyzet" minOccurs="1" maxOccurs="15"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="Szemelyek">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Szemely" type="Szemely" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>


    <!-- Kulcsok -->

    <xs:key name="AllomasID">
      <xs:selector xpath=".//Mentoallomas"/>
      <xs:field xpath="@ID"/>
    </xs:key>
    
    <xs:key name="Sz_ID">
      <xs:selector xpath=".//Szemelyzet"/>
      <xs:field xpath="@Sz_ID"/>
    </xs:key>

    <xs:keyref name="AllomasIDref2" refer="AllomasID">
      <xs:selector xpath=".//Jarmu"/>
      <xs:field xpath="@AllomasID"/>
    </xs:keyref>

    <xs:keyref name="SzemelyzetIDref1" refer="Sz_ID">
      <xs:selector xpath=".//Hasznalja"/>
      <xs:field xpath="@Sz_ID"/>
    </xs:keyref>
    
    <xs:keyref name="JarmuIDref1" refer="JarmuID">
      <xs:selector xpath=".//Hasznalja"/>
      <xs:field xpath="@JarmuID"/>
    </xs:keyref>
    
    <xs:keyref name="AllomasIDref1" refer="AllomasID">
      <xs:selector xpath=".//Szemely"/>
      <xs:field xpath="@MentoA"/>
    </xs:keyref>
    
    <xs:key name="TAJ">
      <xs:selector xpath=".//Szemely"/>
      <xs:field xpath="@TAJ"/>
    </xs:key>

    <xs:key name="JarmuID">
      <xs:selector xpath=".//Jarmu"/>
      <xs:field xpath="@J_ID"/>
    </xs:key>




  </xs:element>



  <!-- Komplex tÃ­pusok -->
  <xs:complexType name="Mentoallomas">
    <xs:sequence>
      <xs:element name="varos" type="xs:string"/>
      <xs:element name="megye" type="xs:string"/>
      <xs:element name="autok_szama" type="xs:int"/>
    </xs:sequence>
    <xs:attribute name="ID" type="xs:int" use="required"/>
  </xs:complexType>

  <xs:complexType name="Jarmu">
    <xs:sequence>
      <xs:element name="Rendszam" type="xs:string"/>
      <xs:element name="Uzemanyagszint" type="xs:int"/>
      <xs:element name="Tankolni_kell" type="xs:byte"/>
      <xs:element name="Evjarat" type="xs:int"/>
    </xs:sequence>
    <xs:attribute name="ID" type="xs:int" use="required"/>
    <xs:attribute name="AllomasID" type="xs:int" use="required"/>
  </xs:complexType>

  <xs:complexType name="Szemelyzet">
    <xs:sequence>
      <xs:element name="Tesztelo" type="xs:string"/>
      <xs:element name="Sofor" type="xs:string"/>
      <xs:element name="Menetido" type="xs:int"/>
    </xs:sequence>
    <xs:attribute name="Sz_ID" type="xs:int" use="required"/>
  </xs:complexType>


  <xs:complexType name="Szemely">
    <xs:sequence>
      <xs:element name="nev" type="xs:string"/>
      <xs:element name="Szuletesi" type="Szuletesi"/>
      <xs:element name="Lakcim" type="xs:string"/>
      <xs:element name="Kontakt" type="xs:byte"/>
      <xs:element name="Telefonszam" type="xs:string"/>
      <xs:element name="Tunet" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="TAJ" type="xs:int" use="required"/>
    <xs:attribute name="MentoA" type="xs:int" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="Hasznalja">
    <xs:attribute name="Sz_ID" type="xs:int" use="required"/>
    <xs:attribute name="JarmuID" type="xs:int" use="required"/>
  </xs:complexType>

  <xs:complexType name="Szuletesi">
    <xs:sequence>
      <xs:element name="Hely">
        <xs:simpleType>
          <xs:restriction base="xs:string"> </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Ido">
        <xs:simpleType>
          <xs:restriction base="xs:date"> </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>


</xs:schema>

=== lyukasgumi/KLJDUJ_XMLgyak/XMLTaskKLJDUJ/XMLkljduj.xml
<?xml version="1.0" encoding="UTF-8"?>
<Covid19onkenteslogisztika xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="XMLSchemaKLJDUJ.xsd">
    <Mentoallomasok>

        <Mentoallomas ID="1">
            <varos>Miskolc</varos>
            <megye>Borsod-Abauj-Zemplen</megye>
            <autok_szama>2</autok_szama>
        </Mentoallomas>

        <Mentoallomas ID="2">
            <varos>Debrecen</varos>
            <megye>Hajdu-Bihar</megye>
            <autok_szama>3</autok_szama>
        </Mentoallomas>
    </Mentoallomasok>

    <Jarmuvek>

        <Jarmu JID="101" AllomasID="1">
            <Rendszam>MZG101</Rendszam>
            <Uzemanyagszint>50</Uzemanyagszint>
            <Tankolni_kell> 1</Tankolni_kell>
            <Evjarat>1999</Evjarat>
        </Jarmu>

        <Jarmu JID="102" AllomasID="1">
            <Rendszam>MZG102</Rendszam>
            <Uzemanyagszint>72</Uzemanyagszint>
            <Tankolni_kell> 1</Tankolni_kell>
            <Evjarat>2004</Evjarat>
        </Jarmu>

        <Jarmu JID="104" AllomasID="2">
            <Rendszam>MRT156</Rendszam>
            <Uzemanyagszint>30</Uzemanyagszint>
            <Tankolni_kell> 0</Tankolni_kell>
            <Evjarat>1995</Evjarat>
        </Jarmu>

        <Jarmu JID="105" AllomasID="2">
            <Rendszam>MRT157</Rendszam>
            <Uzemanyagszint>44</Uzemanyagszint>
            <Tankolni_kell> 1</Tankolni_kell>
            <Evjarat>2003</Evjarat>
        </Jarmu>

        <Jarmu JID="106" AllomasID="2">
            <Rendszam>MRT158</Rendszam>
            <Uzemanyagszint>52</Uzemanyagszint>
            <Tankolni_kell> 1</Tankolni_kell>
            <Evjarat>2008</Evjarat>
        </Jarmu>

    </Jarmuvek>
    
    <Hasznalat_Lista>
        <Hasznalja Sz_ID="1001" JarmuID="101"/>
        <Hasznalja Sz_ID="1002" JarmuID="101"/>
        <Hasznalja Sz_ID="1004" JarmuID="102"/>
        <Hasznalja Sz_ID="1004" JarmuID="104"/>
    </Hasznalat_Lista>
    
    <Szemelyzetek>
        <Szemelyzet Sz_ID="1001">
            <Tesztelo>Obrzut Szabina</Tesztelo>
            <Sofor>Kovacs Antal Doman</Sofor>
            <Menetido>7</Menetido>
        </Szemelyzet>

        <Szemelyzet Sz_ID="1002">
            <Tesztelo>Ocsai Greta</Tesztelo>
            <Sofor>Nadhazy Gergely</Sofor>
            <Menetido>9</Menetido>
        </Szemelyzet>

        <Szemelyzet Sz_ID="1003">
            <Tesztelo>Bodolai Erno</Tesztelo>
            <Sofor>Jaszai Denes</Sofor>
            <Menetido>5</Menetido>
        </Szemelyzet>

        <Szemelyzet Sz_ID="1004">
            <Tesztelo>Balogh Virag</Tesztelo>
            <Sofor>Molnar Janos</Sofor>
            <Menetido>10</Menetido>
        </Szemelyzet>

        <Szemelyzet Sz_ID="1005">
            <Tesztelo>Jandl Bojana</Tesztelo>
            <Sofor>Nagy Imre</Sofor>
            <Menetido>7</Menetido>
        </Szemelyzet>
    </Szemelyzetek>


    <Szemelyek>
        <Szemely TAJ="115744619" MentoA="1">
            <nev>Kádár Pál</nev>
            <Szuletesi>
                <Hely>Miskolc</Hely>
                <Ido>1981-12-11</Ido>
            </Szuletesi>
            <Lakcim>4220, Hajdúböszörmény, Mester utca, 12/B</Lakcim>
            <Kontakt>0</Kontakt>
            <Telefonszam>06706755521</Telefonszam>
            <Tunet>köhögés</Tunet>
            <Tunet>láz</Tunet>
        </Szemely>

        <Szemely TAJ="115764618" MentoA="1">
            <nev>Bisztricki Áron</nev>
            <Szuletesi>
                <Hely>Eger</Hely>
                <Ido>1998-11-12</Ido>
            </Szuletesi>
            <Lakcim>3304, Felnémet, Köztársaság utca, 4</Lakcim>
            <Kontakt>1</Kontakt>
            <Telefonszam>06706755521</Telefonszam>
        </Szemely>

        <Szemely TAJ="116467287" MentoA="2">
            <nev>Sirankó Boldizsár</nev>
            <Szuletesi>
                <Hely>Kaposvár</Hely>
                <Ido>2000-12-23</Ido>
            </Szuletesi>
            <Lakcim>7522, Kaposújlak, Dózsa GYörgy utca, 22</Lakcim>
            <Kontakt>0</Kontakt>
            <Telefonszam>06706755521</Telefonszam>
            <Tunet>köhögés</Tunet>
            <Tunet>láz</Tunet>
        </Szemely>

    </Szemelyek>


</Covid19onkenteslogisztika>

=== lyukasgumi/KLJDUJ_XMLgyak/XMLTaskKLJDUJ/XmlFeladatKLJDUJ/xml_feleves_feladat/XMLkljduj.updated.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><Covid19onkenteslogisztika xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaKLJDUJ.xsd">
    <Mentoallomasok>

        <Mentoallomas ID="1">
            <varos>Miskolc</varos>
            <megye>Borsod-Abauj-Zemplen</megye>
            <autok_szama>2</autok_szama>
        </Mentoallomas>

        <Mentoallomas ID="2">
            <varos>Debrecen</varos>
            <megye>Hajdu-Bihar</megye>
            <autok_szama>3</autok_szama>
        </Mentoallomas>
    </Mentoallomasok>

    <Jarmuvek>

        <Jarmu AllomasID="1" JID="101">
            <Rendszam>MZG101</Rendszam>
            <Uzemanyagszint>55</Uzemanyagszint>
            <Tankolni_kell>1.0</Tankolni_kell>
            <Evjarat>1999</Evjarat>
        </Jarmu>

        <Jarmu AllomasID="1" JID="102">
            <Rendszam>MZG102</Rendszam>
            <Uzemanyagszint>72</Uzemanyagszint>
            <Tankolni_kell>0</Tankolni_kell>
            <Evjarat>2004</Evjarat>
        </Jarmu>

        <Jarmu AllomasID="2" JID="104">
            <Rendszam>MRT156</Rendszam>
            <Uzemanyagszint>30</Uzemanyagszint>
            <Tankolni_kell>1.0</Tankolni_kell>
            <Evjarat>1995</Evjarat>
        </Jarmu>

        <Jarmu AllomasID="2" JID="105">
            <Rendszam>MRT157</Rendszam>
            <Uzemanyagszint>44</Uzemanyagszint>
            <Tankolni_kell>1.0</Tankolni_kell>
            <Evjarat>2003</Evjarat>
        </Jarmu>

        <Jarmu AllomasID="2" JID="106">
            <Rendszam>MRT158</Rendszam>
            <Uzemanyagszint>52</Uzemanyagszint>
            <Tankolni_kell>1.0</Tankolni_kell>
            <Evjarat>2008</Evjarat>
        </Jarmu>

    </Jarmuvek>
    
    <Hasznalat_Lista>
        <Hasznalja JarmuID="101" Sz_ID="1001"/>
        <Hasznalja JarmuID="101" Sz_ID="1002"/>
        <Hasznalja JarmuID="102" Sz_ID="1004"/>
        <Hasznalja JarmuID="104" Sz_ID="1004"/>
    </Hasznalat_Lista>
    
    <Szemelyzetek>
        <Szemelyzet Sz_ID="1001">
            <Tesztelo>Obrzut Szabina</Tesztelo>
            <Sofor>Kovacs Antal Doman</Sofor>
            <Menetido>7</Menetido>
        </Szemelyzet>

        <Szemelyzet Sz_ID="1002">
            <Tesztelo>Ocsai Greta</Tesztelo>
            <Sofor>Nadhazy Gergely</Sofor>
            <Menetido>9</Menetido>
        </Szemelyzet>

        <Szemelyzet Sz_ID="1003">
            <Tesztelo>Bodolai Erno</Tesztelo>
            <Sofor>Jaszai Denes</Sofor>
            <Menetido>5</Menetido>
        </Szemelyzet>

        <Szemelyzet Sz_ID="1004">
            <Tesztelo>Balogh Virag</Tesztelo>
            <Sofor>Molnar Janos</Sofor>
            <Menetido>10</Menetido>
        </Szemelyzet>

        <Szemelyzet Sz_ID="1005">
            <Tesztelo>Jandl Bojana</Tesztelo>
            <Sofor>Nagy Imre</Sofor>
            <Menetido>7</Menetido>
        </Szemelyzet>
    </Szemelyzetek>


    <Szemelyek>
        <Szemely MentoA="1" TAJ="115744619">
            <nev>Kádár Pál</nev>
            <Szuletesi>
                <Hely>Miskolc</Hely>
                <Ido>1981-12-11</Ido>
            </Szuletesi>
            <Lakcim>4220, Hajdúböszörmény, Mester utca, 12/B</Lakcim>
            <Kontakt>0</Kontakt>
            <Telefonszam>06706755521</Telefonszam>
            <Tunet>köhögés</Tunet>
            <Tunet>láz</Tunet>
        </Szemely>

        <Szemely MentoA="1" TAJ="115764618">
            <nev>Bisztricki Áron</nev>
            <Szuletesi>
                <Hely>Eger</Hely>
                <Ido>1998-11-12</Ido>
            </Szuletesi>
            <Lakcim>3304, Felnémet, Köztársaság utca, 4</Lakcim>
            <Kontakt>1</Kontakt>
            <Telefonszam>06706755521</Telefonszam>
        </Szemely>

        <Szemely MentoA="2" TAJ="116467287">
            <nev>Sirankó Boldizsár</nev>
            <Szuletesi>
                <Hely>Kaposvár</Hely>
                <Ido>2000-12-23</Ido>
            </Szuletesi>
            <Lakcim>7522, Kaposújlak, Dózsa GYörgy utca, 22</Lakcim>
            <Kontakt>1</Kontakt>
            <Telefonszam>06706755521</Telefonszam>
            <Tunet>köhögés</Tunet>
            <Tunet>láz</Tunet>
        </Szemely>

    </Szemelyek>


</Covid19onkenteslogisztika>
